export const FETCH_TODOS = "FETCH_TODOS"

export const NEW_USER_REGISTER_REQUESTED = "NEW_USER_REGISTER_REQUESTED"
export const NEW_USER_REGISTER_SUCCEDED = "NEW_USER_REGISTER_SUCCEDED"
export const NEW_USER_REGISTER_FAILED = "NEW_USER_REGISTER_FAILED"

export const GET_ALL_USERS_REQUESTED = "GET_ALL_USERS_REQUESTED";
export const GET_ALL_USERS_SUCCEDED = "GET_ALL_USERS_SUCCEDED";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";