export const FETCH_TODOS = "FETCH_TODOS"

export const SIGN_IN_ANON = "SIGN_IN_ANON"; 
export const SIGN_OUT = "SIGN_OUT"

export const FETCH_SESSIONS_FOR_USER = "FETCH_SESSIONS_FOR_USER";
export const FETCH_ALL_SESSIONS = "FETCH_ALL_SESSIONS";

export const CREATE_SESSION = "CREATE_SESSION";

export const SUMBIT_VOTE = "SUMBIT_VOTE";