export const FETCH_TODOS = 'FETCH_TODOS';

export const SIGN_IN = 'SIGN_IN_ANON';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_SESSIONS_FOR_USER = 'FETCH_SESSIONS_FOR_USER';
export const FETCH_ALL_SESSIONS = 'FETCH_ALL_SESSIONS';

export const CREATE_SESSION = 'CREATE_SESSION';
export const FETCH_SESSION = 'FETCH_SESSION';
export const FETCH_SESSION_ENROLMENT = "FETCH_SESSION_ENROLMENT";

export const SUMBIT_VOTE = 'SUMBIT_VOTE';
export const GET_ALL_VOTES_FOR_SESSION = "GET_ALL_VOTES_FOR_SESSION";

export const CREATE_USER = 'CREATE_USER';
export const GET_USER = "GET_USER";

export const GET_ALL_FEEDBACKS_FOR_SESSION = "GET_ALL_FEEDBACKS_FOR_SESSION";
